API tests added
nccr-itmo/FEDOT.Web pull request #12
Opened 2021-02-04 19:44 UTC by nicl-nno

Добавлен пример текста на GET-метод
Попробовал добавить travis

2021-02-05 14:15 UTC, J3FALL requested changes

2021-02-05 14:15 UTC, J3FALL commented on .travis.yml
> +  - pytest -s
Думаю, можно просто скопировать часть github-action для сборки проекта.
Основу можно взять отсюда практически as-is:
https://github.com/nccr-itmo/FEDOT/blob/master/.github/workflows/manual-build.yml

2021-02-05 14:15 UTC, J3FALL commented on test/test_meta.py
> +                'clustering']) == set(tasks)
Pycharm подсказал, что можно упростить строчку:
![image](https://user-images.githubusercontent.com/7864250/107044570-87dc7880-67d5-11eb-93b7-3b6090eea216.png)

2021-02-05 14:15 UTC, J3FALL commented on test/conftest.py
> +    return app
Хм, не понял по коду - а как тут поднимается сервер для тестов?
В test_meta.py никаких вызовов нет, но вроде инстанс поднимается.

2021-02-05 14:20 UTC, nicl-nno commented on test/conftest.py
> +    return app
Это pytest-flask так умеет https://pytest-flask.readthedocs.io/en/latest/tutorial.html

2021-02-08 13:17 UTC, J3FALL approved these changes

2021-02-08 13:34 UTC, merged