New tests for API added
nccr-itmo/FEDOT.Web pull request #14
Opened 2021-02-08 18:34 UTC by nicl-nno

Simple tests added for the all new endpoints (meta, data, chains, composer)

2021-02-08 18:34 UTC, pep8speaks commented
Hello @nicl-nno! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:









* In the file [`test/test_composer.py`](https://github.com/nccr-itmo/FEDOT.Web/blob/4ed34bc2909350bc883ba00422bc5151a97f22c3/test/test_composer.py):

> [Line 7:80](https://github.com/nccr-itmo/FEDOT.Web/blob/4ed34bc2909350bc883ba00422bc5151a97f22c3/test/test_composer.py#L7): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (95 > 79 characters)



* In the file [`test/test_meta.py`](https://github.com/nccr-itmo/FEDOT.Web/blob/4ed34bc2909350bc883ba00422bc5151a97f22c3/test/test_meta.py):

> [Line 12:80](https://github.com/nccr-itmo/FEDOT.Web/blob/4ed34bc2909350bc883ba00422bc5151a97f22c3/test/test_meta.py#L12): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 13:80](https://github.com/nccr-itmo/FEDOT.Web/blob/4ed34bc2909350bc883ba00422bc5151a97f22c3/test/test_meta.py#L13): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (100 > 79 characters)
> [Line 20:80](https://github.com/nccr-itmo/FEDOT.Web/blob/4ed34bc2909350bc883ba00422bc5151a97f22c3/test/test_meta.py#L20): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 30:80](https://github.com/nccr-itmo/FEDOT.Web/blob/4ed34bc2909350bc883ba00422bc5151a97f22c3/test/test_meta.py#L30): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 31:80](https://github.com/nccr-itmo/FEDOT.Web/blob/4ed34bc2909350bc883ba00422bc5151a97f22c3/test/test_meta.py#L31): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (95 > 79 characters)
> [Line 38:80](https://github.com/nccr-itmo/FEDOT.Web/blob/4ed34bc2909350bc883ba00422bc5151a97f22c3/test/test_meta.py#L38): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)

2021-02-15 09:30 UTC, J3FALL requested changes

2021-02-15 09:30 UTC, J3FALL commented on test/test_composer.py
> +               ['individuals']['ind_1']['objs']) > 0
Тут можно извлечь переменные с поясняющими названиями, станет чуть понятнее и менее громоздко.

2021-02-15 09:30 UTC, J3FALL commented on test/test_meta.py
> +    assert 'MAE' in regression_metrics
Я бы разделил это на 2 отдельных функции, почему бы и нет.

2021-02-15 09:30 UTC, J3FALL commented on test/test_meta.py
> +    assert 'knnreg' in regression_models
Здесь тоже можно на 2 функции разделить

2021-02-15 09:30 UTC, J3FALL commented on app/chains/service.py
> +    with open(f'{project_root()}/data/mocked_jsons/chain.json') as f:
Поправь форматирование здесь.

2021-02-15 20:29 UTC, nicl-nno commented on test/test_composer.py
> +               ['individuals']['ind_1']['objs']) > 0
[Done](https://github.com/nccr-itmo/FEDOT.Web/pull/14/files#diff-4ac495d0112097750b08262eb2031e09fcb18b714d7c4e22d7f91eb45229ea0cR1-R14)

2021-02-15 20:29 UTC, nicl-nno commented on test/test_meta.py
> +    assert 'MAE' in regression_metrics
Разделил

2021-02-15 20:29 UTC, nicl-nno commented on test/test_meta.py
> +    assert 'knnreg' in regression_models
Разделил

2021-02-15 20:30 UTC, nicl-nno commented on app/chains/service.py
> +    with open(f'{project_root()}/data/mocked_jsons/chain.json') as f:
А что ты тут имел в виду? Путь формировать иначе?

2021-02-16 08:55 UTC, J3FALL commented on app/chains/service.py
> +    with open(f'{project_root()}/data/mocked_jsons/chain.json') as f:
Проще - там была проблема с форматированием пробелов и импортов.
Теперь все ок.

2021-02-16 08:56 UTC, J3FALL approved these changes

2021-02-16 09:38 UTC, merged