D3.js-compatible chain structure export implemented
nccr-itmo/FEDOT.Web pull request #16
Opened 2021-03-01 11:22 UTC by nicl-nno

2021-03-02 07:48 UTC, J3FALL requested changes

2021-03-02 07:48 UTC, J3FALL commented on app/api/chains/service.py
> +        node = dict()
А есть какой-то профит использовать dict()
Вместо {} ?

У Иры прост тоже видел, хотя мне казалось, что dict - это более устаревшая версия.

2021-03-02 07:48 UTC, J3FALL commented on app/api/chains/service.py
> +def _chain_to_graph_info(chain):
Может быть, имеет смысл тогда выделить отдельный класс ChainView или ChainSchema?
И эта функция будет внутри конструктора.

2021-03-02 07:48 UTC, J3FALL commented on test/test_chains.py
> +    assert len(history_json['links']) > 0
Странно, но этот тест у меня падает, а в дебаге почему-то нет поля links:
![image](https://user-images.githubusercontent.com/7864250/109615319-d535d680-7b44-11eb-91c8-d81a9a732aa3.png)

2021-03-02 08:34 UTC, nicl-nno commented on app/api/chains/service.py
> +        node = dict()
![image](https://user-images.githubusercontent.com/5711814/109620734-45475b00-7b4b-11eb-8733-8fbeb9f5fd2c.png)

PyCharm почему-то так рекомендует

2021-03-02 08:47 UTC, J3FALL commented on app/api/chains/service.py
> +        node = dict()
окей, понял

2021-03-02 17:52 UTC, nicl-nno commented on app/api/chains/service.py
> +def _chain_to_graph_info(chain):
ChainGraphSchema создал, но ходу не придумал, как это перенести в её конструктор. Есть какой-то пример?

Пока [отправил](https://github.com/nccr-itmo/FEDOT.Web/pull/16/files#diff-60c42cca08f09c297323c6504a5177cb521d28e5e69781c8aeb71801f3bae2a3R55-R64) в контроллер эту логику.

2021-03-02 17:52 UTC, nicl-nno commented on test/test_chains.py
> +    assert len(history_json['links']) > 0
Fixed

2021-03-09 10:34 UTC, pep8speaks commented
Hello @nicl-nno! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`app/api/chains/chain_convert_utils.py`](https://github.com/nccr-itmo/FEDOT.Web/blob/9fa1c03be7f8cf60d38c5a3885687d572d0da593/app/api/chains/chain_convert_utils.py):

> [Line 10:80](https://github.com/nccr-itmo/FEDOT.Web/blob/9fa1c03be7f8cf60d38c5a3885687d572d0da593/app/api/chains/chain_convert_utils.py#L10): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 67:80](https://github.com/nccr-itmo/FEDOT.Web/blob/9fa1c03be7f8cf60d38c5a3885687d572d0da593/app/api/chains/chain_convert_utils.py#L67): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)
> [Line 76:80](https://github.com/nccr-itmo/FEDOT.Web/blob/9fa1c03be7f8cf60d38c5a3885687d572d0da593/app/api/chains/chain_convert_utils.py#L76): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (105 > 79 characters)
> [Line 79:80](https://github.com/nccr-itmo/FEDOT.Web/blob/9fa1c03be7f8cf60d38c5a3885687d572d0da593/app/api/chains/chain_convert_utils.py#L79): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (91 > 79 characters)
> [Line 84:80](https://github.com/nccr-itmo/FEDOT.Web/blob/9fa1c03be7f8cf60d38c5a3885687d572d0da593/app/api/chains/chain_convert_utils.py#L84): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 86:80](https://github.com/nccr-itmo/FEDOT.Web/blob/9fa1c03be7f8cf60d38c5a3885687d572d0da593/app/api/chains/chain_convert_utils.py#L86): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (91 > 79 characters)
> [Line 104:80](https://github.com/nccr-itmo/FEDOT.Web/blob/9fa1c03be7f8cf60d38c5a3885687d572d0da593/app/api/chains/chain_convert_utils.py#L104): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)









* In the file [`test/test_chain_conversion.py`](https://github.com/nccr-itmo/FEDOT.Web/blob/9fa1c03be7f8cf60d38c5a3885687d572d0da593/test/test_chain_conversion.py):

> [Line 13:80](https://github.com/nccr-itmo/FEDOT.Web/blob/9fa1c03be7f8cf60d38c5a3885687d572d0da593/test/test_chain_conversion.py#L13): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (94 > 79 characters)

2021-03-25 09:48 UTC, J3FALL requested changes

2021-03-25 09:48 UTC, J3FALL commented on test/test_chain_conversion.py
> +    assert initial_chain.root_node.descriptive_id == chain_from_graph.root_node.descriptive_id
Слушай, а можешь вытащить полученный json=graph в отдельный файл?
Ну, т.е. то, что что получается в результате этих строчек:
```
initial_chain = Chain()
initial_chain.load(f'{project_root()}/data/mocked_jsons/chain.json')
graph = chain_to_graph(initial_chain)
json = json.dumps(graph)
```

А то я пытался протестить эндпоинт с валидацией, но не нашел готового json-а для этого.
Думаю, резонно его сохранить в data для примеров.

2021-03-25 09:48 UTC, J3FALL commented on app/api/chains/controller.py
> +                          edges=chain_graph['edges'])
Смотри, не очень уловил тут суть:
Вроде как chain_to_graph должен преобразовывать представление fedot-цепочки (chain) в web-graph структуру (т.е. ChainGraph). Однако, здесь дополнительно идет преобразование chain_graph (видимо, словаря) в объект ChainGraph.
Почему нельзя сразу в сервисах (ну или в скрипте chain_utils_convert.py) возвращать ChainGraph?

2021-03-25 09:48 UTC, J3FALL commented on app/api/chains/models.py
> +    nodes: List
Этот класс, кажется, нигде не используется в проекте.

2021-03-25 18:47 UTC, nicl-nno commented on app/api/chains/models.py
> +    nodes: List
Убрал.

2021-03-25 18:54 UTC, nicl-nno commented on test/test_chain_conversion.py
> +    assert initial_chain.root_node.descriptive_id == chain_from_graph.root_node.descriptive_id
Добавил в graph_example.json в data

2021-03-25 18:54 UTC, nicl-nno commented on app/api/chains/controller.py
> +                          edges=chain_graph['edges'])
Перенес ChainGraph в chain_utils_convert (в сервисы не стал - всё-таки ChainGraph это сущность другого уровня, кмк).

Но назначение uid оставил в ChainsIdResource - т.к. функция конвертации про id ничего не знает.

2021-03-26 08:57 UTC, J3FALL approved these changes

2021-03-26 10:11 UTC, merged