Grid fs
nccr-itmo/FEDOT.Web pull request #64
Opened 2021-08-24 09:19 UTC by Sash0check

Added grid_fs for storing pipelines and history of composing.

2021-08-24 09:19 UTC, pep8speaks commented
Hello @Sash0check! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:











* In the file [`init/init_pipelines.py`](https://github.com/nccr-itmo/FEDOT.Web/blob/16ad692708794428d823ba16acaf08d8210e1bfa/init/init_pipelines.py):

> [Line 74:5](https://github.com/nccr-itmo/FEDOT.Web/blob/16ad692708794428d823ba16acaf08d8210e1bfa/init/init_pipelines.py#L74): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare 'except'

2021-08-24 12:51 UTC, nicl-nno requested changes

2021-08-24 12:51 UTC, nicl-nno commented on init/init_history.py
>      _init_composer_history_for_case(db=db, history_id='oil', dataset_name='oil',
Кажется будет нагляднее, если mock_list станет возвращаемым значением.

2021-08-24 12:51 UTC, nicl-nno commented on init/init_history.py
> +                print('history dict_fitted_operations are mocked')
А что тут происходит? Почему и в pipelines.json, и в dict_fitted_operations.json добавляется одно и тоже? Ну и лучше все действия, связанные с моками, вынести в отдельныу функции.

2021-08-25 05:59 UTC, Sash0check commented on init/init_history.py
>      _init_composer_history_for_case(db=db, history_id='oil', dataset_name='oil',
будет нагляднее, но тогда придется ручками собирать все значения из каждого вызова функции в список, как буд-то не оч удобно)

2021-08-25 05:59 UTC, Sash0check commented on init/init_history.py
> +                print('history dict_fitted_operations are mocked')
это злая копипаста) сейчас поправлю)

2021-08-25 06:23 UTC, Sash0check commented on init/init_history.py
> +                print('history dict_fitted_operations are mocked')
https://github.com/nccr-itmo/FEDOT.Web/blob/be04c2eb0e2356aa6b49a153babd651858115c6b/init/init_history.py#L49-L55

2021-08-25 06:28 UTC, Sash0check commented on init/init_history.py
> +                print('history dict_fitted_operations are mocked')
поправил и вынес в отдельную функцию (во всех скриптах)
https://github.com/nccr-itmo/FEDOT.Web/blob/d48f00620c7092338b0e9c734f406aeef5fd24b1/init/init_history.py#L36-L59

2021-08-25 10:31 UTC, nicl-nno commented on init/init_history.py
> +                print('history dict_fitted_operations are mocked')
Вроде можно не открывать файл дважды, если делать как тут: https://stackoverflow.com/questions/6648493/how-to-open-a-file-for-both-reading-and-writing

2021-08-25 10:31 UTC, nicl-nno commented on init/init_history.py
>      _init_composer_history_for_case(db=db, history_id='oil', dataset_name='oil',
Ну вроде это сводится к mock_list.extend(_init_composer_history_for_case(...))? Или что-то ещё нужно?

2021-08-29 18:10 UTC, Sash0check commented on init/init_history.py
>      _init_composer_history_for_case(db=db, history_id='oil', dataset_name='oil',
ну да, это и есть ручное добавление в список, которое мне кажется не очень лаконичным) но да в плане наглядности так лучше)

2021-08-30 17:02 UTC, nicl-nno approved these changes

2021-08-30 17:02 UTC, merged