Dummy endpoints for metadata and history
nccr-itmo/FEDOT.Web pull request #7
Opened 2021-01-27 21:42 UTC by nicl-nno

Добавил endpoint-ы, иллюстрирующие обсужденные сегодня моменты:

meta/model_types/<task_type>- для типов моделей (берутся из фреймворка)
data/datasets/all - для датасетов (захардкожены)
composer/history/<dataset_id> - для истории композера (берется из статического json-a)
/chains/<uid> - полная структура модели (берется из статического json-a)
/chains/add/{graph_structure} - заглушка для создания цепочки на основе присланного с фронтенда описания топологии (с новым UID или существующим, если уже есть цепочка с аналогичной структурой)

2021-01-27 21:42 UTC, pep8speaks commented
Hello @nicl-nno! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`fedot_app/basic_functions.py`](https://github.com/nccr-itmo/FEDOT.Web/blob/d6905884e9c913ae9694dfbe30f210a8769602de/fedot_app/basic_functions.py):

> [Line 5:80](https://github.com/nccr-itmo/FEDOT.Web/blob/d6905884e9c913ae9694dfbe30f210a8769602de/fedot_app/basic_functions.py#L5): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (97 > 79 characters)
> [Line 10:80](https://github.com/nccr-itmo/FEDOT.Web/blob/d6905884e9c913ae9694dfbe30f210a8769602de/fedot_app/basic_functions.py#L10): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (112 > 79 characters)

* In the file [`fedot_app/server.py`](https://github.com/nccr-itmo/FEDOT.Web/blob/d6905884e9c913ae9694dfbe30f210a8769602de/fedot_app/server.py):

> [Line 9:80](https://github.com/nccr-itmo/FEDOT.Web/blob/d6905884e9c913ae9694dfbe30f210a8769602de/fedot_app/server.py#L9): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (100 > 79 characters)
> [Line 108:80](https://github.com/nccr-itmo/FEDOT.Web/blob/d6905884e9c913ae9694dfbe30f210a8769602de/fedot_app/server.py#L108): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)

2021-01-29 15:27 UTC, nicl-nno commented
Перенс ендпоинты в новую структуру.

2021-02-01 11:02 UTC, J3FALL requested changes

2021-02-01 11:02 UTC, J3FALL commented on app/composer/entities.py
> +class ComposingHistory:
Не, это не удобно совсем.
Нужно возвращать полноценный json, а не json с полем в виде string, где вшит json )
![image](https://user-images.githubusercontent.com/7864250/106450254-fa77ec00-6495-11eb-9a9b-949bf1e2fcdb.png)

2021-02-01 11:03 UTC, J3FALL commented
Тесты тоже бы не помешали на новый код

2021-02-01 11:04 UTC, nicl-nno commented
> Тесты тоже бы не помешали на новый код

Только на тот, что в service? Или будем тестить сами эндпоинты?

2021-02-01 11:05 UTC, nicl-nno commented on requirements.txt
> +tensorflow==2.2.0
С tensorflow==2.1.0, прописанным в fedot для python<3.8, flask не работает (https://github.com/tensorflow/tensorflow/issues/34607).

2021-02-01 12:04 UTC, J3FALL commented
> > Тесты тоже бы не помешали на новый код
> 
> Только на тот, что в service? Или будем тестить сами эндпоинты?

По-хорошему, и на то, и на другое.

2021-02-01 12:11 UTC, nicl-nno commented
> По-хорошему, и на то, и на другое.

Предлагаю тогда на первое время ограничиться тестированием эндоинтов - чтобы точно покрыть всю внешнюю функциональность, но и при этом чуть сэкономить времени. А сервисы уже попозже, когда всё установится.

Но тогда мне нужен 1 пример такого теста, чтоб было понятнее, как должно выглядеть.

2021-02-01 15:21 UTC, nicl-nno commented on app/composer/entities.py
> +class ComposingHistory:
Поменял на [такое](https://github.com/nccr-itmo/FEDOT.Web/pull/7/files#diff-8f43f6e8ba5c90835ae06b933777e2fd703b0bac2f30d0943ff47715e3703b2eR5-R9).

2021-02-01 15:21 UTC, nicl-nno commented on app/composer/controller.py
> +    def get(self, dataset_id) -> ComposingHistory:
[Поменял ](https://github.com/nccr-itmo/FEDOT.Web/pull/7/files#diff-c12f545fd2c46a8b23a5b08be5f48da8fd2dd921e3c0b2a53c0499e59d350948R17)везде на dataset_name для единообразция с названием поля Dataset. 
Это уникальное название датасета (потом оно также будет храниться внутри объекта Case с описанием прикладого примера).

2021-02-01 15:21 UTC, nicl-nno commented on app/data/entities.py
> +from dataclasses import dataclass
Ок, поменял.

2021-02-01 15:21 UTC, nicl-nno commented on app/meta/entities.py
> +class ModelName:
Поменял на ModelInfo - чтобы не было [путаницы ](https://github.com/nccr-itmo/FEDOT.Web/pull/7/files#diff-071d81c25c062f0e2ed0ddabb924a1babe12bcae08e492af8dbb88be65c9eac3R10-R13)в FEDOT-объектами.

2021-02-01 15:21 UTC, nicl-nno commented on app/meta/controller.py
> +        model_names = [ModelName(_) for _ in get_model_names(task)]
[Реализовал ](https://github.com/nccr-itmo/FEDOT.Web/pull/7/files#diff-071d81c25c062f0e2ed0ddabb924a1babe12bcae08e492af8dbb88be65c9eac3R4-R7)в виде паре task_name (уникальный идентификатор-название)/display_name(для отображения в интерфейсе). Но пока они одинаковы по значениям.

2021-02-01 15:21 UTC, nicl-nno commented on app/meta/controller.py
> +        tasks = [Task(task_name) for task_name in list(task_dict.keys())]
Ну если на уровень сервиса можно выносить классы типа Task, то ок, [поменял](https://github.com/nccr-itmo/FEDOT.Web/pull/7/files#diff-f12255e207e16a28ed5702ca1d07f6ae36ed0cced931d43f3e26cdbf08466e64R40-R42).

2021-02-04 15:49 UTC, J3FALL commented on app/meta/controller.py
> +        model_names = [ModelName(_) for _ in get_model_names(task)]
Все еще кажется странным, но окей, пусть будет пока так.

2021-02-04 16:14 UTC, J3FALL approved these changes

2021-02-04 16:14 UTC, J3FALL commented on app/chains/models.py
> +from flask import request
Обрати, плз, внимание, что у некоторых эндпоинтах описание совпадают.
Немного путает.

2021-02-04 16:22 UTC, J3FALL commented
> Предлагаю тогда на первое время ограничиться тестированием эндоинтов - чтобы точно покрыть всю внешнюю функциональность, но и при этом чуть сэкономить времени. А сервисы уже попозже, когда всё установится.
> 
> Но тогда мне нужен 1 пример такого теста, чтоб было понятнее, как должно выглядеть.

В исходной статье есть пример, как можно тестить отдельные слои, в т.ч. и контроллеры:
http://alanpryorjr.com/2019-05-20-flask-api-example/

Вот тут пример, как можно замокать сервис и тестить именно котроллер:
![image](https://user-images.githubusercontent.com/7864250/106922194-d8909a80-671d-11eb-8a82-c9260f7e6417.png)
Тут flask_client прямо имитирует запросы к api.
Вот тут еще есть полезные советы, что-то схожее: https://flask.palletsprojects.com/en/1.1.x/testing/
Это как один из вариантов.
Есть альтернативный вариант - в тесте делать setup, в котором создается полноценный инстанс flask-сервера (через нашу функцию create_app c ключом test) и в тестах уже делаются запросы к эндпоинтам через requests.

2021-02-04 16:25 UTC, nicl-nno commented
>Есть альтернативный вариант - в тесте делать setup, в котором создается полноценный инстанс flask-сервера (через нашу функцию create_app c ключом test) и в тестах уже делаются запросы к эндпоинтам через requests.

Ну мне он как-то больше нравится, выглядит как меньше кода надо писать. Давай тогда в след. PR-е так и сделаю.
Контроллеры со сложной логикой тоже можно отдельно протестить, но пока вроде таких нет.

2021-02-04 16:26 UTC, J3FALL commented
> > Есть альтернативный вариант - в тесте делать setup, в котором создается полноценный инстанс flask-сервера (через нашу функцию create_app c ключом test) и в тестах уже делаются запросы к эндпоинтам через requests.
> 
> Ну мне он как-то больше нравится, выглядит как меньше кода надо писать. Давай тогда в след. PR-е так и сделаю.
> Контроллеры со сложной логикой тоже можно отдельно протестить, но пока вроде таких нет.

Хорошо

2021-02-04 17:39 UTC, merged