Analytics service is now refactored
nccr-itmo/FEDOT.Web pull request #75
Opened 2021-09-17 12:18 UTC by IIaKyJIuH

In the refactoring process of the service, the first step was to walk through the code of the service and try to type it so to get some understanding on what's going on there. Then, we would create a bunch of tests to obtain current resulting states and afterwards use them to match answers from the refactored version. At last, the service itself was written in "pythonic" way, i.e. using list/dict comprehensions, standard functions, and trying not to repeat ourselves.

Only two files are relevant:
1. app/api/analytics/service.py
2. test/unit/test_analytics_service.py

2021-09-17 12:18 UTC, pep8speaks commented
Hello @IIaKyJIuH! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





* In the file [`app/api/analytics/service.py`](https://github.com/nccr-itmo/FEDOT.Web/blob/1d1e251f167f99cda1ac7a462a7e1c8923b6a8e2/app/api/analytics/service.py):

> [Line 141:51](https://github.com/nccr-itmo/FEDOT.Web/blob/1d1e251f167f99cda1ac7a462a7e1c8923b6a8e2/app/api/analytics/service.py#L141): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 141:53](https://github.com/nccr-itmo/FEDOT.Web/blob/1d1e251f167f99cda1ac7a462a7e1c8923b6a8e2/app/api/analytics/service.py#L141): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 168:24](https://github.com/nccr-itmo/FEDOT.Web/blob/1d1e251f167f99cda1ac7a462a7e1c8923b6a8e2/app/api/analytics/service.py#L168): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 168:26](https://github.com/nccr-itmo/FEDOT.Web/blob/1d1e251f167f99cda1ac7a462a7e1c8923b6a8e2/app/api/analytics/service.py#L168): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals













* In the file [`main.py`](https://github.com/nccr-itmo/FEDOT.Web/blob/1d1e251f167f99cda1ac7a462a7e1c8923b6a8e2/main.py):

> [Line 28:1](https://github.com/nccr-itmo/FEDOT.Web/blob/1d1e251f167f99cda1ac7a462a7e1c8923b6a8e2/main.py#L28): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

2021-09-20 07:49 UTC, nicl-nno commented on app/api/analytics/service.py
> +    Dict[str, Dict[str, Any]]
Не уверен, что есть смыл настолько сложные type hint-ы расписывать - они не оособо читаемы

>Union[int, Integral]
Вроде в объявленный выше Integral и так входит int.

2021-09-20 07:50 UTC, nicl-nno commented on app/api/analytics/service.py
> +    ]] = [
А зачем тут детализировать тип? Это же дублирует то что выше.

2021-09-20 07:58 UTC, nicl-nno commented
![image](https://user-images.githubusercontent.com/5711814/133971708-22245c6c-645b-4868-a31f-2876883a391c.png)

Пара лишних файлов из фронтенда прилипли.

2021-09-20 08:11 UTC, nicl-nno requested changes

2021-09-20 08:11 UTC, nicl-nno commented on test/unit/test_analytics_service.py
> +    assert result == etalon, f"Chart dicts aren't equal: {result} != {etalon}"
Вроде у etalon в английском немного другой смысл. Проще назвать в стиле correct_result.

2021-09-20 08:11 UTC, nicl-nno commented on test/unit/test_analytics_service.py
> +        }
Несколько смущает что тут дублируется куча кода из основной функции. 

Может проще хранить словари с правильными значениями в виде JSON-ов вместо множества ChartInputCase?

2021-09-20 08:11 UTC, nicl-nno commented on test/unit/test_analytics_service.py
> +from dataclasses import dataclass
Файл в целом очень длинный, лучше вынести моки и прочее в отдельный файл.

2021-09-20 08:11 UTC, nicl-nno commented on test/unit/test_analytics_service.py
> +        is_base: bool = False  # non-existing field
А для чего это поле?

2021-09-20 08:11 UTC, nicl-nno commented on test/unit/test_analytics_service.py
> +def test_test_prediction_for_pipeline(
А почему test_test?

2021-09-20 08:11 UTC, nicl-nno commented on test/unit/test_analytics_service.py
> +    case: PredictionForPipeline,
Не очень понял, почему  case - это PredictionForPipeline

2021-09-20 08:11 UTC, nicl-nno commented on test/unit/test_analytics_service.py
> +    target: Union[str, Callable[[Any], Any]]
Но тут же вроде нет никакого предсказания, почему тогда это prediction.

2021-09-20 08:11 UTC, nicl-nno commented on app/api/analytics/service.py
> +    x_title: str, y_title: str  # TODO: are these needed?
Видимо в текущей версии нет.

2021-09-20 09:09 UTC, IIaKyJIuH commented on app/api/analytics/service.py
> +    Dict[str, Dict[str, Any]]
Согласен, наворочено получилось, упростил

2021-09-20 09:12 UTC, IIaKyJIuH commented on app/api/analytics/service.py
> +    history: OptHistory = composer_history_for_case(case_id)
Вот тут я бы поспорил.
В среде разработки, конечно, тип переменной выведется, но если смотреть логи гита в текстовом файле или просто код на телефоне, скажем? Думаю, не такой это уж и редкий кейс.

2021-09-20 09:13 UTC, IIaKyJIuH commented on app/api/analytics/service.py
> +    obs: npt.NDArray
Подойдёт, кстати, да, как раз сегодня переделывал

2021-09-20 09:20 UTC, nicl-nno commented on app/api/analytics/service.py
> +    history: OptHistory = composer_history_for_case(case_id)
Ну современная разработка ПО без IDE встречается довольно редко)

Но основная проблема в другом: у тебя эти прописанные вручную типы рано или поздно неизбежно рассинхронизируются со временем, т.к. при изменении сигнатуры функции ты не сможешь вспомнить все места, где указал косвенно связанный с ним тип переменной в других частях кода. 

Поэтому и доверять им все равно не выйдет. Это как устаревающие комментарии.

2021-09-20 09:24 UTC, IIaKyJIuH commented on test/unit/test_analytics_service.py
> +    case: PredictionForPipeline,
Этот класс (но есть похожие случаи) используется исключительно для этого теста.

Мне показалось, что если назвать его с подстрокой как и у самого теста, то будет проще найти его через поиск по проекту.

2021-09-20 09:25 UTC, IIaKyJIuH commented on test/unit/test_analytics_service.py
> +def test_test_prediction_for_pipeline(
Я тестировал все функции по их названию в самом файле analytics/service.py, там была функция с префиксом "test", поэтому пришлось записать так.

Исправить?

2021-09-20 09:25 UTC, IIaKyJIuH commented on test/unit/test_analytics_service.py
> +        is_base: bool = False  # non-existing field
Это просто mock-поле, если так можно выразиться, тестировать все кейсы проще...по крайней мере, мне)

2021-09-20 09:26 UTC, IIaKyJIuH commented on test/unit/test_analytics_service.py
> +        x_title="x",
Тут согласен, спасибо, что обратил внимание

2021-09-20 09:28 UTC, nicl-nno commented on test/unit/test_analytics_service.py
> +    case: PredictionForPipeline,
Ну вот из названия не очень очевидна семантика класса.

>будет проще найти его через поиск по проекту.

Ну пока в IDE есть find usages, найти класс не проблема. Опять же, можно разбить этот файл на несколько, тогда навигация станет проще.

2021-09-20 09:30 UTC, IIaKyJIuH commented on app/api/analytics/service.py
> +        y_baseline = list(baseline_prediction.predict) if baseline_prediction else None  # And maybe use .tolist()?
Проверил в колабе скорость работы преобразований на листах питона и на массивах numpy:
![image](https://user-images.githubusercontent.com/38308131/133981330-d9e7ae8a-f643-4dbd-bdd3-c53ab25e4b21.png)

По-моему, разница налицо

2021-09-20 09:33 UTC, nicl-nno commented on test/unit/test_analytics_service.py
> +def test_test_prediction_for_pipeline(
Можно переформулировать название исходной функции, раз такое дело. Кажется там уточнение про test не очень важно.

2021-09-20 09:35 UTC, nicl-nno commented on app/api/analytics/service.py
> +        y_baseline = list(baseline_prediction.predict) if baseline_prediction else None  # And maybe use .tolist()?
Так, ну вроде list() быстрее чем .tolist()? Или ты про что-то другое?

2021-09-20 09:36 UTC, IIaKyJIuH commented on app/api/analytics/service.py
> +    history: OptHistory = composer_history_for_case(case_id)
Теперь понял

2021-09-20 09:41 UTC, nicl-nno commented on test/unit/test_analytics_service.py
> +        is_base: bool = False  # non-existing field
![image](https://user-images.githubusercontent.com/5711814/133982605-0e75e66a-d209-45ca-81fa-97508b754ff4.png)

Вот даже из кода не очень понятно, что же оно значит.

2021-09-20 09:43 UTC, IIaKyJIuH commented on test/unit/test_analytics_service.py
> +    case: PredictionForPipeline,
Про разбиения файла согласен, это в планах, название класса попробую сделать семантичным.

2021-09-20 09:50 UTC, IIaKyJIuH commented on app/api/analytics/service.py
> +        y_baseline = list(baseline_prediction.predict) if baseline_prediction else None  # And maybe use .tolist()?
У `list()` миллисекунды, а у `.tolist()` микросекунды же.

Получается, что `.tolist()` заканчивает работу раньше...Ну и вообще `.tolist()` у меня отработал за минуту-две, а `list()` я ждал минут 10

2021-09-21 07:19 UTC, IIaKyJIuH commented on app/api/analytics/service.py
> +    obs: npt.NDArray
Хотя, с другой стороны, `np.ndarray` не получается шаблонизировать, поэтому, возможно, есть смысл всё же использовать `npt.NDArray`, как думаешь?

2021-09-21 08:00 UTC, IIaKyJIuH commented on test/unit/test_analytics_service.py
> +        }
Он дублируется лишь потому, что изначально код до рефакторинга в файле `analytics/service.py` тестировался с помощью данной функции и именно с этим кодом.
Таким образом, данный код является эталонным и поэтому дальнейшие изменения кода в `analytics/service.py` должны в теории проходить этот тест.

2021-09-21 08:27 UTC, IIaKyJIuH commented on test/unit/test_analytics_service.py
> +        }
Насчёт JSON-ов не очень понял.

1. Я храню не только правильные значения, но и данные, которые подаются на вход в тестируемые функции.
2. Думаю для тестов, наперекор практикам программирования, повторение кода не так страшно, потому что в данном случае оно обеспечивает наглядность тест-кейсов при возникновении ошибок.

2021-09-21 08:32 UTC, IIaKyJIuH commented on test/unit/test_analytics_service.py
> +    assert result == etalon, f"Chart dicts aren't equal: {result} != {etalon}"
Согласен, переименовал

2021-09-21 14:59 UTC, nicl-nno commented on app/api/analytics/service.py
> +        y_baseline = list(baseline_prediction.predict) if baseline_prediction else None  # And maybe use .tolist()?
![image](https://user-images.githubusercontent.com/5711814/134194288-f807dd24-dd0d-441a-981a-ad662b6160fd.png)

Тогда странно, вроде примерах разница не столь значительна. 

В любом случае, в этом примера для любого разумного размера данных затраты времени будет непринципиальны.
Пусть будет tolist.

2021-09-21 15:12 UTC, nicl-nno commented on test/unit/test_analytics_service.py
> +        }
Вот ты тестируешь функцию _make_chart_dicts. Она на выходе выдает словарь x-y-type-name, на вход принимает ChartInputCase.

И вроде бы логичнее сравнивать результат выполнеения функции с заранее сохраненным словарем такой же структуры, а не с результатом сложных преобразований etalon_series.

Иначе тест сводится к тому, что в нём просто повторяется вся логика тестируемой функции - что приводит к высой вероятности ошибки в коде самого теста (т.к. у него та же сложность, что и у тестируемой функции). Также, такой тест сложно поддерживать - при изменении логики функции нужно будет не только эталонные результаты скорректировать, но и логику теста, что сложнее.

2021-09-22 08:01 UTC, IIaKyJIuH commented on test/unit/test_analytics_service.py
> +        }
Теперь понял, что нужно сделать

2021-09-23 12:33 UTC, nicl-nno commented on app/api/analytics/service.py
> +    obs: npt.NDArray
В основном фреймворке используется везде np.ndarray, поэтому проще так. Вроде в этом месте шаблонизация не особо нужна.

2021-09-24 07:07 UTC, IIaKyJIuH commented on app/api/analytics/service.py
> +    ]] = [
Упростил, но всё же оставил типизацию, потому что возвращаемый тип не просто этот объект, а тапл
[Ссылка на кусок](https://github.com/nccr-itmo/FEDOT.Web/blob/a7e15619e4cf108b37bd5354d1aa9f50dd314003/app/api/analytics/service.py#L49)

2021-09-24 07:08 UTC, IIaKyJIuH commented
> ![image](https://user-images.githubusercontent.com/5711814/133971708-22245c6c-645b-4868-a31f-2876883a391c.png)
> 
> Пара лишних файлов из фронтенда прилипли.

Убрал лишние файлы из фронтенда

2021-09-24 07:09 UTC, IIaKyJIuH commented on app/api/analytics/service.py
> +        max_y: float = max(_process_y_value(max(y)) for y in ys) * 1.05
Пофиксил

2021-09-24 07:10 UTC, IIaKyJIuH commented on app/api/analytics/service.py
> +    obs: npt.NDArray
Перевёл на простой `np.ndarray`

2021-09-24 07:12 UTC, IIaKyJIuH commented on test/unit/test_analytics_service.py
> +        is_base: bool = False  # non-existing field
[Переименовал](https://github.com/nccr-itmo/FEDOT.Web/blob/a7e15619e4cf108b37bd5354d1aa9f50dd314003/test/unit/fixtures/analytics_service_fixtures.py#L110)

2021-09-24 07:17 UTC, IIaKyJIuH commented on test/unit/test_analytics_service.py
> +def test_test_prediction_for_pipeline(
[Исправил название тестовой функции](https://github.com/nccr-itmo/FEDOT.Web/blob/a7e15619e4cf108b37bd5354d1aa9f50dd314003/test/unit/test_analytics_service.py#L596)
[И исходной, со всеми её использованиями в других местах](https://github.com/nccr-itmo/FEDOT.Web/blob/a7e15619e4cf108b37bd5354d1aa9f50dd314003/app/api/analytics/service.py#L128)

2021-09-24 07:23 UTC, IIaKyJIuH commented on test/unit/test_analytics_service.py
> +    case: PredictionForPipeline,
Разбил весь тестовый файл на папки с фикстурами и моками (`test/unit/fixtures` и `test/unit/mocks` соответственно)
["Семантизировал" название этого класса](https://github.com/nccr-itmo/FEDOT.Web/blob/a7e15619e4cf108b37bd5354d1aa9f50dd314003/test/unit/test_analytics_service.py#L597) и всех остальных, использующихся в других тест-кейсах.

2021-09-24 07:23 UTC, IIaKyJIuH commented on test/unit/test_analytics_service.py
> +    target: Union[str, Callable[[Any], Any]]
[Теперь семантично](https://github.com/nccr-itmo/FEDOT.Web/blob/a7e15619e4cf108b37bd5354d1aa9f50dd314003/test/unit/test_analytics_service.py#L555)

2021-09-24 07:24 UTC, IIaKyJIuH commented on app/api/analytics/service.py
> +    x_title: str, y_title: str  # TODO: are these needed?
Оставить на будущее (некоторые методы передают эти параметры) или вырезать из всех мест?

2021-09-24 08:02 UTC, nicl-nno commented on app/api/analytics/service.py
> +    ]] = [
Пусть будет, но в целом конструкция [{...}] вроде достаточно однозначно дает понять, что это List[Dict]

2021-09-24 08:07 UTC, nicl-nno commented on test/unit/test_analytics_service.py
> +from dataclasses import dataclass
Файл всё ещё длинноват - я бы тут оставил только тесты и небольшие функции, а все вспомогательные классы вынес в отдельный скрипт.

2021-09-24 08:08 UTC, nicl-nno commented on app/api/analytics/service.py
> +    x_title: str, y_title: str  # TODO: are these needed?
Пусть будет, на случай если эти наднные понадобятся на фронтенде.

2021-09-24 09:26 UTC, IIaKyJIuH commented on app/api/analytics/service.py
> +    x_title: str, y_title: str  # TODO: are these needed?
Параметры оставил, `TODO:` коммент убрал

2021-09-24 09:27 UTC, IIaKyJIuH commented on test/unit/test_analytics_service.py
> +        }
Исправил логику, теперь использую предопределённые ответы

2021-09-24 09:49 UTC, IIaKyJIuH commented on test/unit/test_analytics_service.py
> +from dataclasses import dataclass
[Теперь](https://github.com/nccr-itmo/FEDOT.Web/blob/backend_refactoring/test/unit/test_analytics_service.py) лучше?
Оставил только параметрические тестовые функции и входные тесты для них

2021-09-24 09:55 UTC, nicl-nno commented on test/unit/test_analytics_service.py
> +from dataclasses import dataclass
Я бы все равно TestCase вынес в отдельный файл чтобы тест читался лучше - 600 строк всё-таки многовато. Ну и сложно сами тесты искать в таком длинном листинге.

Ну или как альтернатива - создать каталог analytics и положить туда 3 скрипта, в каждом из которых будет один тест и относящиеся к нему TestCase.

2021-09-27 09:35 UTC, IIaKyJIuH commented on test/unit/test_analytics_service.py
> +from dataclasses import dataclass
Сделал второй вариант

2021-09-27 10:52 UTC, nicl-nno approved these changes

2021-09-27 10:54 UTC, merged