Login form
nccr-itmo/FEDOT.Web pull request #8
Opened 2021-01-28 12:28 UTC by Sash0check

- Added basic authentification with google
- Added ouath2 authentification with google
- Added swagger prototype

2021-02-02 16:21 UTC, pep8speaks commented
Hello @Sash0check! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`app/__init__.py`](https://github.com/nccr-itmo/FEDOT.Web/blob/bbf9f28a03d12a5390a795e83c509d2b3cdfcfa7/app/__init__.py):

> [Line 35:5](https://github.com/nccr-itmo/FEDOT.Web/blob/bbf9f28a03d12a5390a795e83c509d2b3cdfcfa7/app/__init__.py#L35): [E306](https://duckduckgo.com/?q=pep8%20E306) expected 1 blank line before a nested definition, found 0





* In the file [`app/mod_api/__init__.py`](https://github.com/nccr-itmo/FEDOT.Web/blob/bbf9f28a03d12a5390a795e83c509d2b3cdfcfa7/app/mod_api/__init__.py):

> [Line 7:63](https://github.com/nccr-itmo/FEDOT.Web/blob/bbf9f28a03d12a5390a795e83c509d2b3cdfcfa7/app/mod_api/__init__.py#L7): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file









* In the file [`app/mod_auth/config.py`](https://github.com/nccr-itmo/FEDOT.Web/blob/bbf9f28a03d12a5390a795e83c509d2b3cdfcfa7/app/mod_auth/config.py):

> [Line 2:80](https://github.com/nccr-itmo/FEDOT.Web/blob/bbf9f28a03d12a5390a795e83c509d2b3cdfcfa7/app/mod_auth/config.py#L2): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (92 > 79 characters)
> [Line 8:33](https://github.com/nccr-itmo/FEDOT.Web/blob/bbf9f28a03d12a5390a795e83c509d2b3cdfcfa7/app/mod_auth/config.py#L8): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

* In the file [`app/mod_auth/controller.py`](https://github.com/nccr-itmo/FEDOT.Web/blob/bbf9f28a03d12a5390a795e83c509d2b3cdfcfa7/app/mod_auth/controller.py):

> [Line 3:80](https://github.com/nccr-itmo/FEDOT.Web/blob/bbf9f28a03d12a5390a795e83c509d2b3cdfcfa7/app/mod_auth/controller.py#L3): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 30:1](https://github.com/nccr-itmo/FEDOT.Web/blob/bbf9f28a03d12a5390a795e83c509d2b3cdfcfa7/app/mod_auth/controller.py#L30): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 73:1](https://github.com/nccr-itmo/FEDOT.Web/blob/bbf9f28a03d12a5390a795e83c509d2b3cdfcfa7/app/mod_auth/controller.py#L73): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 86:1](https://github.com/nccr-itmo/FEDOT.Web/blob/bbf9f28a03d12a5390a795e83c509d2b3cdfcfa7/app/mod_auth/controller.py#L86): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 95:80](https://github.com/nccr-itmo/FEDOT.Web/blob/bbf9f28a03d12a5390a795e83c509d2b3cdfcfa7/app/mod_auth/controller.py#L95): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (101 > 79 characters)
> [Line 98:80](https://github.com/nccr-itmo/FEDOT.Web/blob/bbf9f28a03d12a5390a795e83c509d2b3cdfcfa7/app/mod_auth/controller.py#L98): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (113 > 79 characters)
> [Line 100:80](https://github.com/nccr-itmo/FEDOT.Web/blob/bbf9f28a03d12a5390a795e83c509d2b3cdfcfa7/app/mod_auth/controller.py#L100): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 117:80](https://github.com/nccr-itmo/FEDOT.Web/blob/bbf9f28a03d12a5390a795e83c509d2b3cdfcfa7/app/mod_auth/controller.py#L117): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (97 > 79 characters)
> [Line 119:80](https://github.com/nccr-itmo/FEDOT.Web/blob/bbf9f28a03d12a5390a795e83c509d2b3cdfcfa7/app/mod_auth/controller.py#L119): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (97 > 79 characters)
> [Line 123:80](https://github.com/nccr-itmo/FEDOT.Web/blob/bbf9f28a03d12a5390a795e83c509d2b3cdfcfa7/app/mod_auth/controller.py#L123): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (99 > 79 characters)
> [Line 124:80](https://github.com/nccr-itmo/FEDOT.Web/blob/bbf9f28a03d12a5390a795e83c509d2b3cdfcfa7/app/mod_auth/controller.py#L124): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (103 > 79 characters)

* In the file [`app/mod_auth/model.py`](https://github.com/nccr-itmo/FEDOT.Web/blob/bbf9f28a03d12a5390a795e83c509d2b3cdfcfa7/app/mod_auth/model.py):

> [Line 8:80](https://github.com/nccr-itmo/FEDOT.Web/blob/bbf9f28a03d12a5390a795e83c509d2b3cdfcfa7/app/mod_auth/model.py#L8): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (91 > 79 characters)
> [Line 15:67](https://github.com/nccr-itmo/FEDOT.Web/blob/bbf9f28a03d12a5390a795e83c509d2b3cdfcfa7/app/mod_auth/model.py#L15): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2021-02-04 16:44 UTC, J3FALL requested changes

2021-02-04 16:44 UTC, J3FALL commented on app/mod_auth/config.py
> +    SCOPE = ['profile', 'email']
Это точно не должно торчать в коде, надо сразу прятать в env-переменные

2021-02-04 16:44 UTC, J3FALL commented on app/mod_auth/controller.py
> +        return 'Could not fetch your information.'
Хм, тут выглядит так, что сразу несколько уровней абстракций смешалось.
Надо подумать, как лучше разделить сущности и операции, связанные с пользователями.

2021-02-09 11:38 UTC, Sash0check commented on app/mod_auth/config.py
> +    SCOPE = ['profile', 'email']
Спрятал https://github.com/nccr-itmo/FEDOT.Web/blob/99a23ab7fd891383d8484c246a1ed4e78a06d002/app/web/mod_auth/config.py#L5-L10

2021-02-09 11:38 UTC, Sash0check commented on app/mod_auth/controller.py
> +        return 'Could not fetch your information.'
Перенес часть логики в service.py https://github.com/nccr-itmo/FEDOT.Web/blob/99a23ab7fd891383d8484c246a1ed4e78a06d002/app/web/mod_auth/controller.py#L55-L62

2021-02-15 11:10 UTC, J3FALL requested changes

2021-02-15 11:10 UTC, J3FALL commented on app/api/auth/controller.py
> +@api.route("/get_token&<string:email>&<string:password>")
Мне кажется, лучше в пути эндпоинта прямо email и pass не передавать, а упаковать его в json.

2021-02-15 11:10 UTC, J3FALL commented on app/api/auth/service.py
> +    new_user = User(email=email, name="name", password=generate_password_hash(password, method='sha256'))
Вот тут можно переменную извлечь, чтобы не было так громоздко.

2021-02-15 11:10 UTC, J3FALL commented on app/api/auth/service.py
> +    )
Тут в скрипте, бтв, форматирование немного не по PEP, обрати внимание.

2021-02-15 11:10 UTC, J3FALL commented on app/api/auth/controller.py
> +class DataSetsResource(Resource):
Кажется, класс некорректно называется - видимо, забыл название поменять?

2021-02-15 11:10 UTC, J3FALL commented on app/web/mod_auth/controller.py
> +            save_changes(user)
save_changes, кажется, резонно делать в сервисах, а не в контроллере.
Например, мне кажется ожидаемым поведение, когда set_user_data что-то в базе меняет у пользователя

2021-02-15 11:10 UTC, J3FALL commented on app/web/mod_auth/controller.py
> +    return redirect(url_for('auth.login'))
Слушай, а можно ре-использовать некоторые методы из api/auth здесь, чтобы код не дублировался?
Мне кажется, что можно, и это упростит понимание кода в целом.

2021-02-15 11:10 UTC, J3FALL commented on app/web/mod_auth/service.py
> +import json
Аналогичный вопрос - вроде можно операции с user-ом вынести в api, чтобы код не дублировался?
А то немного сущности как-будто повторяются, но я не уверен на 100%, что они идентичны.

2021-02-15 11:10 UTC, J3FALL commented on app/web/mod_base/controller.py
> +import json
Оставлю пока коммент, чтобы не забыть.
Немного смущает этот скрипт, да и модуль base в целом.

2021-02-16 11:29 UTC, Sash0check commented on app/web/mod_auth/service.py
> +        user = create_user(user_data)
Эта функция используются для oauth2, в случае успешной аутентификации, если юзера нет создаётся новый. Мб просто вынести эту часть на уровень выше, чтобы название функции соответствовало ее действиям?

2021-02-16 11:37 UTC, Sash0check commented on app/__init__.py
> +        return User.query.get(user_id)
Этот callback отвечает за перезагрузку объекта пользователя. Да можно перенести его в другое место. В контроллер?

2021-02-16 11:41 UTC, Sash0check commented on app/web/mod_auth/controller.py
> +    return redirect(url_for('auth.login'))
Да, кончено, я некоторые методы оттуда и беру, не все заменил просто)

2021-02-16 12:13 UTC, Sash0check commented on app/web/mod_auth/controller.py
> +            save_changes(user)
Я подумал, что если сохранять изменения после работы с каждой бд моделью, то в случае работы с несколькими моделями при возникновении ошибки придется откатываться, а так можно просто в конце сохранять изменения) тут конечно не этот кейс

2021-02-16 14:20 UTC, J3FALL commented on app/__init__.py
> +        return User.query.get(user_id)
Да, звучит разумно, чтобы это было в контроллере.

2021-02-16 14:29 UTC, J3FALL commented on app/web/mod_auth/controller.py
> +            save_changes(user)
Не совсем понял, что ты имеешь в виду.
Попробую перефразировать, поправь меня, если я не прав:
- Если у нас будет кейс, где одновременно производятся операции сразу над несколькими моделями, то резонно их вносить в базу уже вместе?
- Получается аналог транзакций в бд
Если так, то мне кажется, это в любом случае будет в сервисном слое в специальной функции.
Например, какая-нибудь операция типа "swap_models_in_chain(chain, model_first, model_second)"
Если под нее делать отдельный эндпоинт, то в любом случае save_changes логично в сервисе делать.

2021-02-17 13:21 UTC, Sash0check commented on app/create_db_ssl.py
> +    make_ssl_devcert('./ssl', host='localhost')
https://github.com/nccr-itmo/FEDOT.Web/blob/cd101cf6b8e38f0ef2015ae2187811b1452ac674/app/ssl/ssl_config.py#L6-L31

2021-02-17 13:21 UTC, Sash0check commented on app/web/mod_auth/controller.py
> +from flask import Blueprint, render_template, request, url_for, redirect, flash, session
переименовал)

2021-02-17 13:23 UTC, Sash0check commented on app/web/mod_auth/service.py
> +        user = create_user(user_data)
Разделил логику с использованием общих функций
https://github.com/nccr-itmo/FEDOT.Web/blob/cd101cf6b8e38f0ef2015ae2187811b1452ac674/app/web/auth/controller.py#L60-L67

2021-02-17 13:25 UTC, Sash0check commented on app/web/mod_auth/controller.py
> +            save_changes(user)
отправил в сервисы
https://github.com/nccr-itmo/FEDOT.Web/blob/cd101cf6b8e38f0ef2015ae2187811b1452ac674/app/api/auth/service.py#L24

2021-02-17 13:26 UTC, Sash0check commented on app/__init__.py
> +        return User.query.get(user_id)
https://github.com/nccr-itmo/FEDOT.Web/blob/cd101cf6b8e38f0ef2015ae2187811b1452ac674/app/web/auth/controller.py#L15-L17

2021-02-17 13:27 UTC, Sash0check commented on app/api/auth/controller.py
> +@api.route("/get_token&<string:email>&<string:password>")
https://github.com/nccr-itmo/FEDOT.Web/blob/cd101cf6b8e38f0ef2015ae2187811b1452ac674/app/api/auth/controller.py#L14-L22

2021-02-17 13:27 UTC, Sash0check commented on app/api/auth/controller.py
> +class DataSetsResource(Resource):
https://github.com/nccr-itmo/FEDOT.Web/blob/cd101cf6b8e38f0ef2015ae2187811b1452ac674/app/api/auth/controller.py#L15

2021-02-17 13:28 UTC, Sash0check commented on app/web/mod_auth/controller.py
> +    return redirect(url_for('auth.login'))
перенес все операции с пользователем в api

2021-02-21 15:37 UTC, nicl-nno commented
У меня тесты проходят, но при попытке входа через браузер - не подключается, ERR_TIMED_OUT. Надо что-то ещё делать, чтобы работало?

2021-02-25 09:36 UTC, J3FALL commented on app/create_db_ssl.py
> +    make_ssl_devcert('./ssl', host='localhost')
А зачем, кстати, наследоваться от object?

2021-02-25 10:08 UTC, J3FALL requested changes

2021-02-25 10:08 UTC, J3FALL commented on app/web/auth/model.py
> +    created_at = db.Column(db.DateTime, default=datetime.utcnow())
Эти поля должны быть частью объекта, а не класса.
Т.е. либо эти переменные должны быть объявлены в init, либо User должен быть с аннотацией @dataclass

2021-02-25 10:08 UTC, J3FALL commented on app/ssl/ssl_config.py
> +        return self.ssl_cert, self.ssl_key
Добавь, плз, базовые тесты на функции этого класса.

2021-02-25 10:08 UTC, J3FALL commented on app/api/auth/service.py
> +    if not password is None:
Кажется, можно упростить:
`if password`

2021-02-25 10:08 UTC, J3FALL commented on app/api/auth/controller.py
> +        return {"message": "registration successful"}
Смотри, тут аннотация не соответствует всем вариантам return-а.

2021-02-25 10:08 UTC, J3FALL commented on app/api/auth/controller.py
> +            raise Unauthorized("check login data")
А вот при Unauthorized ошибке, пользователь что получит в json-е?

2021-02-25 11:18 UTC, Sash0check commented on app/create_db_ssl.py
> +    make_ssl_devcert('./ssl', host='localhost')
на самом деле не зачем, привычка) архаизм, уберу это)

2021-02-25 12:26 UTC, Sash0check commented on app/api/auth/controller.py
> +            raise Unauthorized("check login data")
вернется response со статусом 401 и json: 
{
  "message": "check login data"
}

2021-02-25 12:55 UTC, Sash0check commented on app/create_db_ssl.py
> +    make_ssl_devcert('./ssl', host='localhost')
https://github.com/nccr-itmo/FEDOT.Web/blob/7236d9f4c070d44ff58879adf5f02f1ca41db1aa/app/ssl/ssl_config.py#L6

2021-02-25 12:55 UTC, Sash0check commented on app/web/auth/model.py
> +    created_at = db.Column(db.DateTime, default=datetime.utcnow())
https://github.com/nccr-itmo/FEDOT.Web/blob/7236d9f4c070d44ff58879adf5f02f1ca41db1aa/app/web/auth/model.py#L9-L13

2021-02-25 12:56 UTC, Sash0check commented on app/ssl/ssl_config.py
> +        return self.ssl_cert, self.ssl_key
https://github.com/nccr-itmo/FEDOT.Web/blob/7236d9f4c070d44ff58879adf5f02f1ca41db1aa/test/test_ssl_config.py#L6
https://github.com/nccr-itmo/FEDOT.Web/blob/7236d9f4c070d44ff58879adf5f02f1ca41db1aa/test/test_ssl_config.py#L16
https://github.com/nccr-itmo/FEDOT.Web/blob/7236d9f4c070d44ff58879adf5f02f1ca41db1aa/test/test_ssl_config.py#L26

2021-02-25 12:57 UTC, Sash0check commented on app/api/auth/controller.py
> +        return {"message": "registration successful"}
https://github.com/nccr-itmo/FEDOT.Web/blob/7236d9f4c070d44ff58879adf5f02f1ca41db1aa/app/api/auth/controller.py#L40-L41

2021-02-25 16:00 UTC, J3FALL commented on app/create_db_ssl.py
> +    make_ssl_devcert('./ssl', host='localhost')
Гуд

2021-02-25 16:02 UTC, J3FALL commented on app/api/auth/controller.py
> +            raise Unauthorized("check login data")
Окей, выглядит разумно.

2021-02-25 16:03 UTC, J3FALL requested changes

2021-02-25 16:03 UTC, J3FALL commented on test/test_ssl_config.py
> +    os.remove(key)
А разве не надо удалять эти файлы после каждого теста?
Я предполагаю, что это можно оформить в tear_down.
А name вынести в константу на уровень всего скрипта, чтобы точно этот файл удалялся.

2021-02-28 10:23 UTC, Sash0check commented on test/test_ssl_config.py
> +    os.remove(key)
Сделал фикстуры для названия файлов
https://github.com/nccr-itmo/FEDOT.Web/blob/fd27176294f4ac2c85938b5818ea44eade27558a/test/conftest.py#L15-L23
и для очистки
https://github.com/nccr-itmo/FEDOT.Web/blob/fd27176294f4ac2c85938b5818ea44eade27558a/test/conftest.py#L26-L30

https://github.com/nccr-itmo/FEDOT.Web/blob/fd27176294f4ac2c85938b5818ea44eade27558a/test/test_ssl_config.py#L6

2021-03-01 10:47 UTC, J3FALL approved these changes

2021-03-01 10:47 UTC, J3FALL commented on test/conftest.py
> +        "key": name + ".key"
замени на f-string.

2021-03-01 11:01 UTC, merged