Changed 'OptHistory' serialization from pickle to json
nccr-itmo/FEDOT.Web pull request #82
Opened 2021-11-11 13:53 UTC by IIaKyJIuH

2021-11-11 18:29 UTC, nicl-nno requested changes

2021-11-11 18:29 UTC, nicl-nno commented on app/api/composer/service.py
> +    _convert_history_opt_graph_to_template(history)
Мб будет  понятнее если эта функция будет возвращать history, а не менять in-place?

2021-11-11 18:29 UTC, nicl-nno commented on app/api/composer/service.py
> +                    pip.link_to_empty_pipeline.unfit()
А это сейчас нужно? Вроде при новом способе импорта истории там optgraph-ы, у которых нет обученного состояния:

![image](https://user-images.githubusercontent.com/5711814/141350077-87353116-f91f-43bb-8434-7a9b4ed71276.png)

2021-11-11 18:29 UTC, nicl-nno commented on init/init_history.py
> +    for i, pipeline_template in enumerate([ind.graph for ind in list(itertools.chain(*history.individuals))]):
Читаемей будет создать список заранее.

2021-11-11 18:29 UTC, nicl-nno commented on app/api/composer/service.py
> +                ind.graph = adapter.restore_as_template(ind.graph, ind.computation_time)
Может вынести циклы for в функцию? А топочти оодинаковых код дважды повторяется.

2021-11-12 07:03 UTC, IIaKyJIuH commented on app/api/composer/service.py
> +                    pip.link_to_empty_pipeline.unfit()
Я не в теме, но разве это состояние не может тоже сериализоваться?

2021-11-12 07:29 UTC, IIaKyJIuH commented on app/api/composer/service.py
> +    _convert_history_opt_graph_to_template(history)
А есть ли смысл возвращать тот же самый `history`, если тут не будет копирования всех полей, а просто изменится поле `graph` в том же самом объекте `history` для каждого индивида?

Может вообще стоит третий вариант найти

2021-11-12 07:33 UTC, IIaKyJIuH commented on init/init_history.py
> +    for i, pipeline_template in enumerate([ind.graph for ind in list(itertools.chain(*history.individuals))]):
Готово

2021-11-12 07:47 UTC, IIaKyJIuH commented on app/api/composer/service.py
> +                ind.graph = adapter.restore_as_template(ind.graph, ind.computation_time)
Вынес в одну функцию

2021-11-12 10:28 UTC, nicl-nno commented on app/api/composer/service.py
> +    _convert_history_opt_graph_to_template(history)
Вот мне кажется что если скопировать и использовать как
pipeline_history = _convert_history_opt_graph_to_template(history)
то будет читаемей и более поддерживаемо в дальнейшем (например, если решим создать отдельный класс PipelineComposingHistory). 

Но не принципиально.

2021-11-12 10:29 UTC, nicl-nno commented on app/api/composer/service.py
> +                    pip.link_to_empty_pipeline.unfit()
Какое именно состояние?

У OptGraph-ов же нет сущности обученных моделей в узлах, которая есть у пайплайна.

2021-11-12 10:30 UTC, nicl-nno commented
В целом осталось починить проблемы, возникающие в тестах, проверить на реальных данных - и можно аппрувать.

2021-11-12 11:08 UTC, IIaKyJIuH commented on app/api/composer/service.py
> +    _convert_history_opt_graph_to_template(history)
Мне тоже это не принципиально, сделал по твоему совету

2021-11-12 11:19 UTC, pep8speaks commented
Hello @IIaKyJIuH! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`app/api/composer/service.py`](https://github.com/nccr-itmo/FEDOT.Web/blob/78900e777a883c67ba0d7abbdcf86ef9646f3b86/app/api/composer/service.py):

> [Line 75:5](https://github.com/nccr-itmo/FEDOT.Web/blob/78900e777a883c67ba0d7abbdcf86ef9646f3b86/app/api/composer/service.py#L75): [E306](https://duckduckgo.com/?q=pep8%20E306) expected 1 blank line before a nested definition, found 0

2021-11-12 11:21 UTC, IIaKyJIuH commented on app/api/composer/service.py
> +                    pip.link_to_empty_pipeline.unfit()
Окей, убрал функцию `unfit_history(...)`

2021-11-19 20:40 UTC, nicl-nno commented on app/api/composer/service.py
> +    def convert_individuals_opt_graphs_to_templates(individuals: List[Individual]) -> List[PipelineTemplate]:
Вот тут кстати стоит вынести вложенную функцию, а то очень запутано смотрится.

2021-11-22 08:02 UTC, IIaKyJIuH commented on app/api/composer/service.py
> +    def convert_individuals_opt_graphs_to_templates(individuals: List[Individual]) -> List[PipelineTemplate]:
Окей, сделал, хотя, по-моему, выглядит как в привычном замыкании

2021-11-22 10:04 UTC, nicl-nno commented
По комментам всё ок.

Добавь ещё плз функцию, которую с диска считывает историю композера для заданного кейса. Чтобы не нужно было каждый раз при init_db.py заново прогонять оптимизацию. 

Заодно проверим, что всё норм работает с новой историей.

2021-11-25 17:15 UTC, nicl-nno commented
Думаю в это PR надо починить тесты и уже мержить его, а дорабатывать отдельно.

2021-11-26 14:03 UTC, nicl-nno approved these changes

2021-11-26 14:07 UTC, merged