Endpoint for the adding of new datasets implemented
nccr-itmo/FEDOT.Web pull request #86
Opened 2021-11-27 20:20 UTC by nicl-nno

- /data/add endpoint for bytes-encoded pandas datasets
- tests structure changed

2021-12-01 09:46 UTC, IIaKyJIuH requested changes

2021-12-01 13:13 UTC, nicl-nno commented on test/endpoints/test_showcase.py
> +from fedot.core.serializers import json_helpers
Эту роль сейчас выполняет бот pep8speaks, но он не всё жестко регламентирует. 
Локально я применяю optimize imports в pycharm-е в дефолтными настройками.

2021-12-01 13:13 UTC, nicl-nno commented on requirements.txt
> +pandas>=1.3.0; python_version >='3.9'
Пока просто скопировал это из FEDOT.

2021-12-01 13:15 UTC, nicl-nno commented on app/api/data/service.py
> +                                                  task=None, target_column='target')
Я убрал указание task для данных при хранении (т.к. это атрибут скорее кейса), поэтому сейчас нужно явно указывать.

Но с task=None - это была устаревшая версия, теперь [так](https://github.com/nccr-itmo/FEDOT.Web/pull/86/files#diff-26a654e25fbe36e00fad20404ff4cc41df3c018edfb9f953321b4da718cb9a8cR51-R66)

2021-12-01 13:32 UTC, nicl-nno commented on app/api/data/controller.py
> +            os.mkdir(data_path)
Так и [сделал](https://github.com/nccr-itmo/FEDOT.Web/pull/86/files#diff-e435d49b8d356f3cdb80d289b362af7d7dd4e8bcc9719d7cf5a8cdc65bf0b7c4R46-R47)

2021-12-01 13:32 UTC, nicl-nno commented on app/api/data/controller.py
> +        test_data.to_csv(Path(dataset_name, f'{dataset_name}_test.csv'))
Так и [сделал](https://github.com/nccr-itmo/FEDOT.Web/pull/86/files#diff-e435d49b8d356f3cdb80d289b362af7d7dd4e8bcc9719d7cf5a8cdc65bf0b7c4R49-R57).

2021-12-01 13:33 UTC, nicl-nno commented on app/api/composer/history_convert_utils.py
> +
А эти ключи вообще нужны после переноса истории в формат OptGraph-ов?

2021-12-01 14:00 UTC, IIaKyJIuH commented on app/api/data/controller.py
> +        test_data.to_csv(Path(dataset_name, f'{dataset_name}_test.csv'))
Красиво

2021-12-01 14:05 UTC, IIaKyJIuH commented on app/api/data/controller.py
> +            pickle.loads(bytes(data_json[content_label], encoding='latin1'))
Не получится ли тоже самое, если не конвертировать в байты, а просто выбрать encoding для loads?
То есть
```
pickle.loads(data_json[content_label], encoding='latin1')
```

2021-12-02 07:00 UTC, IIaKyJIuH commented on app/api/data/service.py
> +                task.task_params = TsForecastingParams(forecast_length=30)
Если `task` выше и конструировался, то точно без параметров, поэтому такая проверка излишняя.
Кроме того, кажется, что установка поля `task_params` должна быть перед загрузкой `data`.

2021-12-02 07:06 UTC, IIaKyJIuH commented on app/api/composer/history_convert_utils.py
> +
Тут дело в том, что на клиенте в `OptGraph`-ы переносятся только индивиды из полей `individuals` и `archive_history` у истории.
В `operator.parent_objects` хранятся изначально `PipelineTemplate`-ы, но на клиенте они переносятся в `Pipeline` из-за чего и возникает такая необходимость в написании`try: ... except: ...`

Поэтому пока что эти ключи нужны

2021-12-02 08:01 UTC, IIaKyJIuH commented on test/endpoints/test_showcase.py
> +from fedot.core.serializers import json_helpers
Думаю, я не один, кто пользуется другой средой разработки, из-за чего возникают несостыковки.
Что скажешь насчёт идеи создания файла `.isort.cfg` в проекте? Чтобы работало для всех одинаково вне зависимости от IDE.
Кажется, пока что хватит таких настроек
![image](https://user-images.githubusercontent.com/38308131/144381108-ef1c4992-ceb8-4684-88eb-6badac84d79c.png)

Возможно, лучше создать даже не `.isort.cfg` а какой-то другой универсальный конфиг файл, чтобы правилам подвергались не только импорты, но и код.

2021-12-02 08:07 UTC, nicl-nno commented on test/endpoints/test_showcase.py
> +from fedot.core.serializers import json_helpers
Ок, давай попробуем, если такой файл действительно подходит для разных IDE.

Вкинь тогда в этот или отдельный PR нужный файл.

2021-12-02 08:09 UTC, nicl-nno commented on app/api/composer/history_convert_utils.py
> +
Это да. Я к тому, что кмк нет смысла унифицировать ID, проще сразу перейти везде к оптграфам (думаю, лучше за рамками этого pr)

2021-12-02 14:18 UTC, nicl-nno commented on app/api/data/controller.py
> +            pickle.loads(bytes(data_json[content_label], encoding='latin1'))
[Done](https://github.com/nccr-itmo/FEDOT.Web/pull/86/files#diff-e435d49b8d356f3cdb80d289b362af7d7dd4e8bcc9719d7cf5a8cdc65bf0b7c4R49-R52)

2021-12-02 14:20 UTC, nicl-nno commented on app/api/data/controller.py
> +            pickle.loads(bytes(data_json[content_label], encoding='latin1'))
Вот кажется для str это не работает:

![image](https://user-images.githubusercontent.com/5711814/144439747-9f924692-09db-4ec5-a52e-b6dedf570632.png)

2021-12-02 14:23 UTC, nicl-nno commented on app/api/data/service.py
> +                task.task_params = TsForecastingParams(forecast_length=30)
Сделал [так](https://github.com/nccr-itmo/FEDOT.Web/pull/86/files#diff-26a654e25fbe36e00fad20404ff4cc41df3c018edfb9f953321b4da718cb9a8cR58-R67) - добавил возможность передачи task_params  снаружи (пока она не востребована, надо будет подумать, как лучше задавать длину прогноза)

2021-12-03 05:47 UTC, IIaKyJIuH commented on app/api/data/controller.py
> +            pickle.loads(bytes(data_json[content_label], encoding='latin1'))
Понял, собственно говоря, даже в документации по `loads` сказано, что нужен 
![image](https://user-images.githubusercontent.com/38308131/144551781-983ea4d9-ec7c-41fa-b277-358f4d8baee3.png)

С другой стороны, получается, что pickle будет кодировать в ASCII, это норм?

2021-12-03 06:00 UTC, IIaKyJIuH commented on app/api/data/service.py
> +                task.task_params = TsForecastingParams(forecast_length=30)
Может тогда сразу передать `task_params` в конструктор `Task(...)`, чтобы не делать лишнюю проверку?

Если выполняется [этот иф](https://github.com/nccr-itmo/FEDOT.Web/pull/86/files#diff-26a654e25fbe36e00fad20404ff4cc41df3c018edfb9f953321b4da718cb9a8cR62), `task` гарантированно не None?

2021-12-03 06:08 UTC, IIaKyJIuH commented on app/api/composer/history_convert_utils.py
> +
Согласен.

2021-12-03 07:38 UTC, IIaKyJIuH commented on test/endpoints/test_showcase.py
> +from fedot.core.serializers import json_helpers
Я поспешил с предложением: в том же `pycharm`-е это можно заставить работать, но совсем неизящно получается (нужно, во-первых, поставить себе `isort`, во-вторых, добавить `external-tool` с `isort`-ом, настроить его правильно, наконец, поставить хоткей на эту тулзу...)

В общем, может быть со временем придумается что-нибудь получше.

2021-12-03 07:39 UTC, IIaKyJIuH approved these changes

2021-12-03 07:44 UTC, IIaKyJIuH requested changes
Нужно зарезолвить уже имеющееся

2021-12-03 13:57 UTC, nicl-nno commented on app/api/data/controller.py
> +            pickle.loads(bytes(data_json[content_label], encoding='latin1'))
Это логика для REST-эндпоинта, там вроде оправдано в текст содержимое полей кодировать.

2021-12-03 14:08 UTC, nicl-nno commented on app/api/data/service.py
> +                task.task_params = TsForecastingParams(forecast_length=30)
Сделал [так](https://github.com/nccr-itmo/FEDOT.Web/pull/86/files#diff-26a654e25fbe36e00fad20404ff4cc41df3c018edfb9f953321b4da718cb9a8cR58-R62), чтобы передавалось сразу в конструктор.

2021-12-06 06:19 UTC, IIaKyJIuH commented on app/api/data/service.py
> +                task.task_params = TsForecastingParams(forecast_length=30)
Красиво

2021-12-06 06:29 UTC, IIaKyJIuH approved these changes

2021-12-06 06:48 UTC, merged