Updated processing of evolutionary operations
nccr-itmo/FEDOT.Web pull request #89
Opened 2022-03-21 14:40 UTC by nicl-nno

- Various improvements for new uids in FEDOT.
- More stable tests

2022-03-21 14:40 UTC, pep8speaks commented
Hello @nicl-nno! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`app/api/composer/history_convert_utils.py`](https://github.com/nccr-itmo/FEDOT.Web/blob/141c5ff3a7fc8ec54c7cf93b19bff5128fa454b2/app/api/composer/history_convert_utils.py):

> [Line 170:5](https://github.com/nccr-itmo/FEDOT.Web/blob/141c5ff3a7fc8ec54c7cf93b19bff5128fa454b2/app/api/composer/history_convert_utils.py#L170): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare 'except'
> [Line 187:5](https://github.com/nccr-itmo/FEDOT.Web/blob/141c5ff3a7fc8ec54c7cf93b19bff5128fa454b2/app/api/composer/history_convert_utils.py#L187): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '

2022-03-22 10:08 UTC, MorrisNein commented on init/init_history.py
> +                print(f'Pipeline processing exception: {ex}')
Вижу, что этот метод может быть вызван через API. 
Результат `print`-а можно будет увидеть в таком случае? Если нет, то нас это волнует?

2022-03-22 10:58 UTC, nicl-nno commented on init/init_history.py
> +                print(f'Pipeline processing exception: {ex}')
В cерверном логе - можно. Ну а пользователю действительно это не особо важно.

2022-03-22 11:24 UTC, MorrisNein approved these changes

2022-03-23 14:28 UTC, IIaKyJIuH requested changes

2022-03-23 14:28 UTC, IIaKyJIuH commented on app/api/composer/history_convert_utils.py
> +                #    print(f'There is no parents for {node["uid"]}')
Тут позже другое сообщение появится?

2022-03-23 14:28 UTC, IIaKyJIuH commented on app/api/composer/history_convert_utils.py
> +        operator_node['tmp_parent_pipelines'] = []
`try...except` конструкция актуальна? Кажется, что ошибок уже быть не должно

2022-03-23 14:28 UTC, IIaKyJIuH commented on app/api/composer/service.py
> +
Может стоит добавить `else` блок на случай если придёт, например, `clustering`?

2022-03-23 14:28 UTC, IIaKyJIuH commented on app/singletons/db_service.py
> +                self._db[collection].delete_many(old_obj_query)
Думаю, по семантике метода лучше использовать тут `.delete_one`

2022-03-23 14:28 UTC, IIaKyJIuH commented on init/init_history.py
> +            pipeline_uid = str(individual.uid)
У индивидов в текущей реализации FEDOT и так `str` тип у идентификатора

2022-03-23 14:28 UTC, IIaKyJIuH commented on requirements.txt
> +scikit_learn>=0.2.4; python_version <= '3.6'
Теперь эта версия питона не актуальна и для FEDOT

2022-03-23 14:28 UTC, IIaKyJIuH commented on test/integration/external_case_creation.py
> +    uid = str(history.individuals[0][0].uid)
Снова лишний каст к `str`

2022-03-23 14:28 UTC, IIaKyJIuH commented on app/api/composer/history_convert_utils.py
> +        pipeline_id = str(individual.uid)
Здесь тоже лишний каст

2022-03-23 16:22 UTC, IIaKyJIuH requested changes

2022-03-23 16:22 UTC, IIaKyJIuH commented on init/init_history.py
> +                            mock_dct['dicts_fitted_operations'].append(dict_fitted_operations)
Предлагаю сделать из `mock_dct['pipelines_dict']` именно словарь вместо списка. 
Во-первых, так будет семантичнее, во-вторых, так можно будет проще реализовать lookup для `pipeline_uid`

2022-03-23 16:22 UTC, IIaKyJIuH commented on app/api/composer/history_convert_utils.py
>          individual = history.individuals[gen_id][ind_id]
Может стоит записать `else` блок в строках 48-52 так, как [здесь](https://github.com/nccr-itmo/FEDOT.Web/blob/mutation_ancestors_fix/app/api/composer/history_convert_utils.py#L50-L55) сделал я? Мне это показалось более безопасным

2022-03-23 16:35 UTC, IIaKyJIuH commented
Добавь ещё тест на проверку правильного количества предков у операций, которые отрисуются.
У меня [уже была заготовка](https://github.com/nccr-itmo/FEDOT.Web/blob/mutation_ancestors_fix/test/integration/test_operators_ancestors.py), возможно, придётся её как-то допилить

2022-03-25 17:14 UTC, nicl-nno commented on app/api/composer/history_convert_utils.py
> +                #    print(f'There is no parents for {node["uid"]}')
Убрал вообще.

2022-03-25 17:15 UTC, nicl-nno commented on app/api/composer/history_convert_utils.py
> +        operator_node['tmp_parent_pipelines'] = []
На всякий случай пока оставил. Добавил сообщене об ошибке.

2022-03-25 17:15 UTC, nicl-nno commented on app/api/composer/service.py
> +
Если ни одно из условий не сработает - available_operationsпросто останется по по умолчанию.

2022-03-25 17:15 UTC, nicl-nno commented on app/singletons/db_service.py
> +                self._db[collection].delete_many(old_obj_query)
Поменял.

2022-03-25 17:15 UTC, nicl-nno commented on init/init_history.py
> +            pipeline_uid = str(individual.uid)
Убрал str и переменную вообще.

2022-03-25 17:17 UTC, nicl-nno commented on init/init_history.py
> +        _save_history_to_path(history, history_path)
Так и [сделал](https://github.com/nccr-itmo/FEDOT.Web/pull/89/files#diff-ed2945cc00bd8390f421ae9908c6a673a50849f1491741d3e068cf9106de4b9dR93).

2022-03-25 17:17 UTC, nicl-nno commented on app/api/composer/history_convert_utils.py
>          individual = history.individuals[gen_id][ind_id]
Сделал [так](https://github.com/nccr-itmo/FEDOT.Web/pull/89/files#diff-be8cc9cab7e218428ca627f184e377ddde41bad36155f98e6e659ed80526ae46R51-R60)

2022-03-25 17:18 UTC, nicl-nno commented on test/integration/external_case_creation.py
> +    uid = str(history.individuals[0][0].uid)
Убрал

2022-03-25 17:18 UTC, nicl-nno commented on requirements.txt
> +scikit_learn>=0.2.4; python_version <= '3.6'
Убрал

2022-03-25 17:19 UTC, nicl-nno commented
> Добавь ещё интеграционный тест на проверку правильного количества предков у операций, которые отрисуются. У меня [уже была заготовка](https://github.com/nccr-itmo/FEDOT.Web/blob/mutation_ancestors_fix/test/integration/test_operators_ancestors.py), возможно, придётся её как-то допилить

Добавил [test_operators_ancestors](https://github.com/nccr-itmo/FEDOT.Web/pull/89/files#diff-60a82a6dde626c45e6ccf66b28cf14cbdcbac13527b4475df718a5c98c606704R1-R28) на его основе.

2022-03-29 08:10 UTC, IIaKyJIuH requested changes

2022-03-29 08:10 UTC, IIaKyJIuH commented on init/init_history.py
> +        pipelines = [i['pipelines_dict'].values() for i in mock_list]
Здесь точно должен сохраняться массив вместо одного пайплайна, как было раньше? 
Не так ли: `[j for i in mock_list for j in i['pipelines_dict'].values()]`?

2022-03-29 11:15 UTC, IIaKyJIuH requested changes

2022-03-29 11:15 UTC, IIaKyJIuH commented on app/api/composer/history_convert_utils.py
> +                else parent_operators_for_ind
Кстати, может записать выражение наоборот, чтобы не писать `not`?
```
parent_operators_for_ind = parent_operators_for_ind if isinstance(parent_operators_for_ind, list) \
                else [parent_operators_for_ind]
```
Конечно, не особо влияет, но без `not` лично у меня получается читать проще.

2022-04-01 17:40 UTC, nicl-nno commented on init/init_history.py
> +        pipelines = [i['pipelines_dict'].values() for i in mock_list]
Поправил.

2022-04-01 17:40 UTC, nicl-nno commented on app/api/analytics/controller.py
> +        pipeline, case = pipeline_by_uid(individual_id), showcase_item_from_db(case_id)
В данном случае это именно pipeline. Но действительно много где путаница с этим, правлю где замечаю.

2022-04-01 17:40 UTC, nicl-nno commented on app/api/composer/history_convert_utils.py
> +                    operator_to_update['tmp_parent_individuals'].append(parents_for_operator)
Да, похоже на то. Поправил.

2022-04-01 17:40 UTC, nicl-nno commented on app/api/composer/history_convert_utils.py
> +                else parent_operators_for_ind
Поменял. Но потом тут можно будет применить новую функцию из FEDOT-а для работы со списками.

2022-04-01 18:58 UTC, IIaKyJIuH approved these changes

2022-04-01 20:22 UTC, merged