Distance from init generation in history
nccr-itmo/FEDOT.Web pull request #90
Opened 2022-04-01 12:56 UTC by MorrisNein

Genotypic convergence now uses "graph edit distance" metric between pipelines.
The convergence of each generation shows distribution of distances from its pipelines to every pipeline of 0-generation.

2022-04-01 12:56 UTC, pep8speaks commented
Hello @MorrisNein! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`app/api/analytics/service.py`](https://github.com/nccr-itmo/FEDOT.Web/blob/8d7111ef50c0344462e544c41600ea2cb51561e5/app/api/analytics/service.py):

> [Line 117:121](https://github.com/nccr-itmo/FEDOT.Web/blob/8d7111ef50c0344462e544c41600ea2cb51561e5/app/api/analytics/service.py#L117): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (122 > 120 characters)

2022-04-01 20:23 UTC, nicl-nno commented
Влил в мастер ops-ветку, можно делать ребейз.

2022-04-02 13:19 UTC, IIaKyJIuH requested changes

2022-04-02 13:19 UTC, IIaKyJIuH commented on app/api/analytics/service.py
> +        for generation in history.individuals:
Не знаю, как должно быть, но точно ли нужно считать расстояния для пайплайнов из 0 поколения?

2022-04-02 13:19 UTC, IIaKyJIuH commented on app/api/composer/history_convert_utils.py
>              prev_pipelines = [n for n in all_nodes if n['type'] == 'individual'
Не про твои изменения, но всё же следует переименовать в `prev_individuals`

2022-04-05 10:27 UTC, MorrisNein commented on app/api/analytics/service.py
> +        for generation in history.individuals:
Я полагаю, @IIaKyJIuH имел в виду, нужна ли нам эта дистаниця для 0 поколения, по сути расстояния между пайплайнами в одном поколении. Это показывает, насколько отличаются друг от друга начальные приближения, так что в целом смысла не лишено.

2022-04-05 10:40 UTC, MorrisNein commented on app/api/composer/history_convert_utils.py
>              prev_pipelines = [n for n in all_nodes if n['type'] == 'individual'
Согласен, поправил

2022-04-05 12:04 UTC, IIaKyJIuH approved these changes

2022-04-11 10:07 UTC, nicl-nno approved these changes

2022-04-11 10:33 UTC, merged